/*
 * GestionePropriEsamiForm.java
 *
 * Created on 24 novembre 2008, 11.59
 */

package studente.gestionePropriEsami;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import operatore.gestioneAppelli.Appello;
import operatore.gestioneUtenti.Studente;

/**
 *
 * @author  e-vampire
 */
public class GestionePropriEsamiForm extends javax.swing.JFrame {
    
    /** Creates new form GestionePropriEsamiForm */
    public GestionePropriEsamiForm(Studente studente) {
        this.studente=studente;
        initComponents();
        this.setDefaultCloseOperation(this.HIDE_ON_CLOSE);
        this.setResizable(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2 - this.getWidth()/2, dim.height/2 - this.getHeight()/2);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        visualizzaAppelliDisponibiliButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("C o f f e e - Gestione Propri Esami");

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        jLabel1.setText("Gestione Propri Esami");

        visualizzaAppelliDisponibiliButton.setText("Visualizza Appelli Disponibili");
        visualizzaAppelliDisponibiliButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visualizzaAppelliDisponibiliButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(visualizzaAppelliDisponibiliButton))
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visualizzaAppelliDisponibiliButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visualizzaAppelliDisponibiliButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visualizzaAppelliDisponibiliButtonMouseClicked
        GestionePropriEsamiControl gpec = new GestionePropriEsamiControl();
        gpec.visualizzaAppelliDisponibili(studente);
    }//GEN-LAST:event_visualizzaAppelliDisponibiliButtonMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton visualizzaAppelliDisponibiliButton;
    // End of variables declaration//GEN-END:variables
    private Studente studente;
 
}
