/*
 * AnalisiCarrieraForm.java
 *
 * Created on 22 novembre 2008, 11.45
 */

package studente.analisiCarriera;

/**
 *
 * @author  e-vampire
 */
public class AnalisiCarrieraForm extends javax.swing.JFrame {
    
    /** Creates new form AnalisiCarrieraForm */
    public AnalisiCarrieraForm() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AnalisiCarrieraTitleLabel = new javax.swing.JLabel();
        studenteLabel = new javax.swing.JLabel();
        nomeStudentelabel = new javax.swing.JLabel();
        matricolaLabel = new javax.swing.JLabel();
        matricolaStudenteLabel = new javax.swing.JLabel();
        visualizzaLibrettoButton = new javax.swing.JButton();
        visualizzaStatisticheButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AnalisiCarrieraTitleLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 24));
        AnalisiCarrieraTitleLabel.setText("Analisi Carriera");

        studenteLabel.setText("Studente: ");

        matricolaLabel.setText("Matricola: ");

        visualizzaLibrettoButton.setText("Visualizza Libretto");
        visualizzaLibrettoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizzaLibrettoButtonActionPerformed(evt);
            }
        });

        visualizzaStatisticheButton.setText("Visualizza Statistiche");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AnalisiCarrieraTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(matricolaLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(matricolaStudenteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(studenteLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(nomeStudentelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(visualizzaLibrettoButton)
                        .addGap(18, 18, 18)
                        .addComponent(visualizzaStatisticheButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AnalisiCarrieraTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studenteLabel)
                    .addComponent(nomeStudentelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matricolaLabel)
                    .addComponent(matricolaStudenteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visualizzaLibrettoButton)
                    .addComponent(visualizzaStatisticheButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visualizzaLibrettoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizzaLibrettoButtonActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_visualizzaLibrettoButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalisiCarrieraForm().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnalisiCarrieraTitleLabel;
    private javax.swing.JLabel matricolaLabel;
    private javax.swing.JLabel matricolaStudenteLabel;
    private javax.swing.JLabel nomeStudentelabel;
    private javax.swing.JLabel studenteLabel;
    private javax.swing.JButton visualizzaLibrettoButton;
    private javax.swing.JButton visualizzaStatisticheButton;
    // End of variables declaration//GEN-END:variables
    
}
