/*
 * HomeStudenteForm.java
 *
 * Created on 22 novembre 2008, 20.11
 */

package studente;

import java.awt.Dimension;
import java.awt.Toolkit;
import operatore.gestioneUtenti.Studente;
import studente.analisiCarriera.AnalisiCarrieraForm;
import studente.gestionePropriEsami.GestionePropriEsamiForm;

/**
 *
 * @author  e-vampire
 */
public class HomeStudenteForm extends javax.swing.JFrame {
    
    /** Creates new form HomeStudenteForm */
    public HomeStudenteForm(Studente studente) {
        this.setTitle("Coffee - Coffee's an Organazier For Friendly Exams Experience");
        this.studente = studente;
        initComponents();
        homeTitle.setText("Benvenuto " + studente.getNome());
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2 - this.getWidth()/2, dim.height/2 - this.getHeight()/2);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeTitle = new javax.swing.JLabel();
        analisiCarrieraButton = new javax.swing.JButton();
        gestionePropriEsamiButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        homeTitle.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        homeTitle.setText("Benvenuto ");

        analisiCarrieraButton.setText("Analisi Carriera");
        analisiCarrieraButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                analisiCarrieraButtonMouseClicked(evt);
            }
        });

        gestionePropriEsamiButton.setText("Gestione Propri Esami");
        gestionePropriEsamiButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestionePropriEsamiButtonMouseClicked(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(analisiCarrieraButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gestionePropriEsamiButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(logoutButton))
                    .addComponent(homeTitle))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(analisiCarrieraButton)
                    .addComponent(gestionePropriEsamiButton)
                    .addComponent(logoutButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void analisiCarrieraButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_analisiCarrieraButtonMouseClicked
        AnalisiCarrieraForm form = new AnalisiCarrieraForm(studente);
        form.setVisible(true);
}//GEN-LAST:event_analisiCarrieraButtonMouseClicked

    private void gestionePropriEsamiButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionePropriEsamiButtonMouseClicked
        GestionePropriEsamiForm exForm = new GestionePropriEsamiForm();
        exForm.setVisible(true);
}//GEN-LAST:event_gestionePropriEsamiButtonMouseClicked

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        //TODO exit alla schermata di login
        System.exit(0);
}//GEN-LAST:event_logoutButtonMouseClicked
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analisiCarrieraButton;
    private javax.swing.JButton gestionePropriEsamiButton;
    private javax.swing.JLabel homeTitle;
    private javax.swing.JButton logoutButton;
    // End of variables declaration//GEN-END:variables
    private Studente studente;
}
