/*
 * RicercaPrenotatiForm.java
 *
 * Created on 27 novembre 2008, 10.36
 */

package docente.gestionePropriAppelli;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import javax.swing.JOptionPane;
import operatore.gestioneAppelli.Appelli;
import operatore.gestioneAppelli.Appello;
import operatore.gestioneAppelli.AppelloControlInterface;
import operatore.gestioneUtenti.Docente;

/**
 *
 * @author  serenity
 */
public class RicercaPrenotatiForm extends javax.swing.JFrame {
    
    /** Creates new form RicercaPrenotatiForm */
    public RicercaPrenotatiForm(Docente docente) {
       
            AppelloControlInterface appContr = null;
            appelli = new Appelli();
            try {
                appContr = (AppelloControlInterface) Naming.lookup("rmi://localhost/GestioneAppelli");
                appelli.setData(appContr.ricercaPropriAppelli(docente));
            }catch(RemoteException e){
                JOptionPane.showMessageDialog(null, "Errore remoto:\n"+e.getMessage());
            }catch(MalformedURLException e){
                JOptionPane.showMessageDialog(null, "URL errato:\n"+e.getMessage());
            }catch(NotBoundException e){
                JOptionPane.showMessageDialog(null, "Nessun Bound per GestioneAppelli:\n"+e.getMessage());
        }
                       
            initComponents();
            this.setDefaultCloseOperation(RicercaPrenotatiForm.HIDE_ON_CLOSE);
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            this.setLocation(dim.width / 2 - this.getWidth() / 2, dim.height / 2 - this.getHeight() / 2);
     
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        appelliTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ricercaPrenotatiButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        prenotatiTable = new javax.swing.JTable();
        registraVotoButton = new javax.swing.JButton();
        registraAssenzaButton = new javax.swing.JToggleButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Coffee - Ricerca Prenotati Form");

        appelliTable.setModel(appelli);
        jScrollPane1.setViewportView(appelliTable);

        jLabel1.setText("Propri Appelli:");

        jLabel2.setText("Selezionare un appello per visualizzare la lista di prenotati");

        ricercaPrenotatiButton.setText("Ricerca Prenotati");
        ricercaPrenotatiButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ricercaPrenotatiButtonMouseClicked(evt);
            }
        });

        jScrollPane3.setViewportView(prenotatiTable);

        registraVotoButton.setText("Registra Voto");
        registraVotoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registraVotoButtonMouseClicked(evt);
            }
        });

        registraAssenzaButton.setText("Registra Assenza");
        registraAssenzaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registraAssenzaButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ricercaPrenotatiButton)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(registraVotoButton)
                        .addGap(18, 18, 18)
                        .addComponent(registraAssenzaButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(ricercaPrenotatiButton)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registraVotoButton)
                    .addComponent(registraAssenzaButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ricercaPrenotatiButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ricercaPrenotatiButtonMouseClicked
        int selectRow=appelliTable.getSelectedRow();
        if(selectRow<0){
            JOptionPane.showMessageDialog(jLabel1, evt, "Nessun Appello selezionato", WIDTH);
        }
        else{
                prenotati=new Prenotati();
                prenotatiTable.setModel(prenotati);
                Appello appSel = appelli.get(selectRow);
                try{
                    GestionePropriAppelliControlInterface prenCont = null;
                    prenCont = (GestionePropriAppelliControlInterface)Naming.lookup("rmi://localhost/GestionePropriAppelli");
                    prenotati.setData(prenCont.ricercaPrenotati(appSel));
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Errore remoto:\n"+e.getMessage());
                }
            }
}//GEN-LAST:event_ricercaPrenotatiButtonMouseClicked

    private void registraVotoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registraVotoButtonMouseClicked
        int appelloSelezionato=appelliTable.getSelectedRow();
        int prenotatoSelezionato=prenotatiTable.getSelectedRow();
        if(appelloSelezionato<0 || prenotatoSelezionato<0){
            JOptionPane.showMessageDialog(null,"Appello o Prenotato non selezionati");
        }
        else{
            RegistraVotoForm registraVotoForm = new RegistraVotoForm(appelli.get(appelloSelezionato),prenotati.get(prenotatoSelezionato));
            registraVotoForm.setVisible(true);
        }
    }//GEN-LAST:event_registraVotoButtonMouseClicked

    private void registraAssenzaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registraAssenzaButtonMouseClicked
        int appelloSelezionato=appelliTable.getSelectedRow();
        int prenotatoSelezionato=prenotatiTable.getSelectedRow();
        if(appelloSelezionato<0 || prenotatoSelezionato<0){
            JOptionPane.showMessageDialog(null,"Appello o Prenotato non selezionati");
        }
        else{
            try{
            GestionePropriAppelliControlInterface gpac = (GestionePropriAppelliControlInterface)Naming.lookup("rmi://localhost/GestionePropriAppelli");
            gpac.RegistraAssenza(appelli.get(appelloSelezionato), prenotati.get(prenotatoSelezionato));
        }catch(RemoteException e){
            JOptionPane.showMessageDialog(null, "Errore connessione remota:\n"+e);
        }catch(MalformedURLException e){
            JOptionPane.showMessageDialog(null, "URL oggetto remoto errato:\n"+e);
        }catch(NotBoundException e){
            JOptionPane.showMessageDialog(null, "Nessun bound per l'oggetto richiesto:\n"+e);
        }
        }
        
    }//GEN-LAST:event_registraAssenzaButtonMouseClicked
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable appelliTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable prenotatiTable;
    private javax.swing.JToggleButton registraAssenzaButton;
    private javax.swing.JButton registraVotoButton;
    private javax.swing.JButton ricercaPrenotatiButton;
    // End of variables declaration//GEN-END:variables
    private Prenotati prenotati;
    private Appelli appelli;
}
