package operatore.gestioneEsami;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author  
 */
public class EsameForm extends javax.swing.JFrame {
    
    /** Creates new form CreaEsameForm */
    public EsameForm() {
        initComponents();
        this.setDefaultCloseOperation(this.HIDE_ON_CLOSE);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2 - this.getWidth()/2, dim.height/2 - this.getHeight()/2);
        this.setResizable(false);
    }
      
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        oreFrontaliField = new javax.swing.JTextField();
        oreLaboratorioField = new javax.swing.JTextField();
        creditiField = new javax.swing.JTextField();
        creaEsameButton = new javax.swing.JButton();
        azzeraCampiButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        semestreField = new javax.swing.JTextField();
        programmaField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setText("Dati per il nuovo esame");

        jLabel2.setText("Nome:");

        jLabel3.setText("Ore frontali:");

        jLabel4.setText("Ore laboratorio:");

        jLabel5.setText("Crediti:");

        jLabel6.setText("Programma");

        oreFrontaliField.setText("0");
        oreFrontaliField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oreFrontaliFieldActionPerformed(evt);
            }
        });

        oreLaboratorioField.setText("0");
        oreLaboratorioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oreLaboratorioFieldActionPerformed(evt);
            }
        });

        creditiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditiFieldActionPerformed(evt);
            }
        });

        creaEsameButton.setText("Invia");
        creaEsameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creaEsameButtonMouseClicked(evt);
            }
        });

        azzeraCampiButton.setText("Azzera Campi");
        azzeraCampiButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                azzeraCampiButtonMouseClicked(evt);
            }
        });

        jLabel7.setText("Semestre:");

        semestreField.setText("1");
        semestreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semestreFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(creaEsameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomeField, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(creditiField)
                            .addComponent(semestreField, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(oreLaboratorioField)
                            .addComponent(oreFrontaliField, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(programmaField)
                            .addComponent(azzeraCampiButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(oreFrontaliField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(oreLaboratorioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(creditiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(semestreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(programmaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(azzeraCampiButton)
                    .addComponent(creaEsameButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oreFrontaliFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oreFrontaliFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_oreFrontaliFieldActionPerformed

    private void oreLaboratorioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oreLaboratorioFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_oreLaboratorioFieldActionPerformed

    private void creditiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditiFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_creditiFieldActionPerformed

    private void azzeraCampiButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_azzeraCampiButtonMouseClicked
        nomeField.setText("");
        oreFrontaliField.setText("");
        oreLaboratorioField.setText("");
        creditiField.setText("");
        programmaField.setText("");
}//GEN-LAST:event_azzeraCampiButtonMouseClicked

    private void creaEsameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creaEsameButtonMouseClicked
        if(nomeField.getText().equals("")) 
            JOptionPane.showMessageDialog(null, "Compilare almeno il campo nome");
        else {
            Esame esame = new Esame();
            esame.setOreFrontali(Integer.parseInt(oreFrontaliField.getText()));
            esame.setNome(nomeField.getText());
            esame.setOreLaboratoro(Integer.parseInt(oreLaboratorioField.getText()));
            esame.setCrediti(Integer.parseInt(creditiField.getText()));
            esame.setProgramma(programmaField.getText());
            esame.setSemestre(Integer.parseInt(semestreField.getText()));
            EsameControl exCont = new EsameControl();
            exCont.creaEsame(esame);
            this.setVisible(false);
        }
}//GEN-LAST:event_creaEsameButtonMouseClicked

    private void semestreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semestreFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_semestreFieldActionPerformed
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton azzeraCampiButton;
    private javax.swing.JButton creaEsameButton;
    private javax.swing.JTextField creditiField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nomeField;
    private javax.swing.JTextField oreFrontaliField;
    private javax.swing.JTextField oreLaboratorioField;
    private javax.swing.JTextField programmaField;
    private javax.swing.JTextField semestreField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
     
}
