package operatore.gestioneEsami;

/**
 *Classe che modella il form per la gestione degli esami, contenente i boundary
 * per le operazioni di creazione, modifica, 
 * @author  
 */

public class GestioneEsamiForm extends javax.swing.JFrame {
    
    /** Creates new form GestioneEsamiForm */
    public GestioneEsamiForm() {
        initComponents();
        this.setTitle("Gestione Esami");
        this.setDefaultCloseOperation(this.HIDE_ON_CLOSE);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creaEsameButton = new javax.swing.JButton();
        ricercaEsameButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        creaEsameButton.setText("Crea Esame");
        creaEsameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creaEsameButtonMouseClicked(evt);
            }
        });

        ricercaEsameButton.setText("Ricerca Esame");

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 24));
        jLabel1.setText("Gestione Esami");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(creaEsameButton)
                        .addGap(18, 18, 18)
                        .addComponent(ricercaEsameButton))
                    .addComponent(jLabel1))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creaEsameButton)
                    .addComponent(ricercaEsameButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creaEsameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creaEsameButtonMouseClicked
        EsameForm esameForm = new EsameForm();
        esameForm.setVisible(true);
    }//GEN-LAST:event_creaEsameButtonMouseClicked
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creaEsameButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton ricercaEsameButton;
    // End of variables declaration//GEN-END:variables
    
}
