/*
 * RicercaPrenotatiForm.java
 *
 * Created on 27 novembre 2008, 10.36
 */

package docente.gestionePropriAppelli;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import operatore.gestioneAppelli.Appelli;
import operatore.gestioneAppelli.Appello;

/**
 *
 * @author  serenity
 */
public class RicercaPrenotatiForm extends javax.swing.JFrame {
    
    /** Creates new form RicercaPrenotatiForm */
    public RicercaPrenotatiForm() {
        prenotati=new Prenotati();
        initComponents();
        this.setDefaultCloseOperation(RicercaPrenotatiForm.HIDE_ON_CLOSE);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2 - this.getWidth()/2, dim.height/2 - this.getHeight()/2);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableAppelli = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ricercaPrenotatiButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Coffee - Ricerca Prenotati Form");

        jScrollPane1.setViewportView(JTableAppelli);

        jLabel1.setText("Propri Appelli:");

        jLabel2.setText("Selezionare un appello per visualizzare la lista di prenotati");

        ricercaPrenotatiButton.setText("Ricerca Prenotati");
        ricercaPrenotatiButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ricercaPrenotatiButtonMouseClicked(evt);
            }
        });

        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ricercaPrenotatiButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(ricercaPrenotatiButton)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ricercaPrenotatiButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ricercaPrenotatiButtonMouseClicked
        int selectRow=JTableAppelli.getSelectedRow();
        if(selectRow<0){
            JOptionPane.showMessageDialog(jLabel1, evt, "Nessun Appello selezionato", WIDTH);
        }
        else{
                Appelli appelli = new Appelli();
                Appello appSel = appelli.get(selectRow);
                GestionePropriAppelliControl prenCont = new GestionePropriAppelliControl();
                prenotati.setData(prenCont.ricercaPrenotati(appSel));
            }
}//GEN-LAST:event_ricercaPrenotatiButtonMouseClicked
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableAppelli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton ricercaPrenotatiButton;
    // End of variables declaration//GEN-END:variables
    private Prenotati prenotati;
}
